elifesciences/eLife-JATS-schematron

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/given-names-tests/given-names-test-5/fail.xml, tests/given-names-tests/given-names-test-5/given-names-test-5.sch, tests/given-names-tests/given-names-test-5/pass.xml, tests/surname-tests/surname-test-4/fail.xml, tests/surname-tests/surname-test-4/pass.xml, tests/surname-tests/surname-test-4/surname-test-4.sch, xspec/schematron.sch, xspec/xspec/schematron-result.html, xspec/xspec/schematron-result.xml
- Apostrophe escape for regex in surname-test-4 and given-names-test-5
=> Apostrophe workaround

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/body-table-label-tests/body-table-label-test-1/body-table-label-test-1.sch, tests/body-table-label-tests/body-table-label-test-1/fail.xml, tests/body-table-label-tests/body-table-label-test-1/pass.xml, xspec/schematron.sch
- account for author ressponse tables
=> [MOD] extend body-table-label-test-1

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/ethics-info/ethics-info-conformity/ethics-info-conformity.sch, tests/ethics-info/ethics-info-conformity/fail.xml, tests/ethics-info/ethics-info-conformity/pass.xml, tests/ethics-tests/ethics-test-1/ethics-test-1.sch, tests/ethics-tests/ethics-test-1/fail.xml, tests/ethics-tests/ethics-test-1/pass.xml, xspec/schematron.sch, xspec/schematron.xspec
- Account for feature 5 template which includes ethics outside of additional info section
=> Feature 5 ethics

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/unlinked-ref-cite/text-v-cite-test/fail.xml, tests/unlinked-ref-cite/text-v-cite-test/pass.xml, tests/unlinked-ref-cite/text-v-cite-test/text-v-cite-test.sch, xspec/schematron.sch
- Account for periodicals (descendant year in unlinked-ref-cite)
=> [MOD] edits

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/abstract-sec-titles/clintrial-conformance-5/fail.xml, tests/abstract-sec-titles/clintrial-conformance-6/clintrial-conformance-6.sch, tests/abstract-sec-titles/clintrial-conformance-6/fail.xml, tests/abstract-sec-titles/clintrial-conformance-6/pass.xml, tests/abstract-tests/abstract-test-5/abstract-test-5.sch, tests/abstract-tests/abstract-test-5/fail.xml, tests/abstract-tests/abstract-test-5/pass.xml, xspec/schematron.sch, xspec/schematron.xspec
- Test for required sections
- include 'Funding:' title check
=> Update clinical trial abstracts

final-JATS-schematron.sch, final-package-JATS-schematron.sch, pre-JATS-schematron.sch, schematron.sch, tests/reply-missing-disp-quote-tests/reply-missing-disp-quote-test-1/fail.xml, tests/reply-missing-disp-quote-tests/reply-missing-disp-quote-test-1/pass.xml, tests/reply-missing-disp-quote-tests/reply-missing-disp-quote-test-1/reply-missing-disp-quote-test-1.sch, xspec/schematron.sch, xspec/schematron.xspec
- Add test for italic blocks in Author response
=> [MOD] add AR test

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/fig-xref-conformance/fig-xref-test-13/fail.xml, test/tests/gen/fig-xref-conformance/fig-xref-test-13/fig-xref-test-13.sch, test/tests/gen/fig-xref-conformance/fig-xref-test-13/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add warning for possible incomplete figure citaiton
=> fig citation

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/ext-link-tests/ext-link-child-test-2/ext-link-child-test-2.sch, test/tests/gen/ext-link-tests/ext-link-child-test-2/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-2/pass.xml, test/tests/gen/ext-link-tests/ext-link-child-test-3/ext-link-child-test-3.sch, test/tests/gen/ext-link-tests/ext-link-child-test-3/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-3/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `ext-link-child-test-2`: exclude non-formatting elems from `xref`
- `ext-link-child-test-3`: error when `copy archived` test included in `ext-link`
=> Add link tests for code forking

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/app-ids/app-id-test-1/app-id-test-1.sch, test/tests/gen/app-ids/app-id-test-1/fail.xml, test/tests/gen/app-ids/app-id-test-1/pass.xml, test/tests/gen/app-ids/app-id-test-2/app-id-test-2.sch, test/tests/gen/app-ids/app-id-test-2/fail.xml, test/tests/gen/app-ids/app-id-test-2/pass.xml, test/tests/gen/ext-link-tests/ext-link-child-test-2/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-2/pass.xml, test/tests/gen/ext-link-tests/ext-link-child-test-3/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-3/pass.xml, test/tests/gen/general-video/final-video-cite/fail.xml, test/tests/gen/general-video/final-video-cite/final-video-cite.sch, test/tests/gen/general-video/final-video-cite/pass.xml, test/tests/gen/general-video/pre-video-cite/fail.xml, test/tests/gen/general-video/pre-video-cite/pass.xml, test/tests/gen/general-video/pre-video-cite/pre-video-cite.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Downgrade `final-video-cite` and update message
- Fix `app-id-test-1` and `app-id-test-2` which used the old appendix id convention
=> minor fixes

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/ext-link-tests/ext-link-child-test-2/ext-link-child-test-2.sch, test/tests/gen/ext-link-tests/ext-link-child-test-2/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-2/pass.xml, test/tests/gen/ext-link-tests/ext-link-child-test-3/ext-link-child-test-3.sch, test/tests/gen/ext-link-tests/ext-link-child-test/ext-link-child-test.sch, test/tests/gen/ext-link-tests/ext-link-child-test/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test/pass.xml, test/tests/gen/ext-link-tests/ext-link-parent-test/ext-link-parent-test.sch, test/tests/gen/ext-link-tests/ext-link-parent-test/fail.xml, test/tests/gen/ext-link-tests/ext-link-parent-test/pass.xml, test/tests/gen/ext-link-tests/url-conformance-test/url-conformance-test.sch, test/tests/gen/ext-link-tests/url-fullstop-report/url-fullstop-report.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Account for normal text embedded with links for ext-link child and parent tests
=> fix ext-link issues

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/dec-letter-reply-tests/dec-letter-reply-test-2/dec-letter-reply-test-2.sch, test/tests/gen/dec-letter-reply-tests/dec-letter-reply-test-2/fail.xml, test/tests/gen/dec-letter-reply-tests/dec-letter-reply-test-2/pass.xml, test/tests/gen/list-item-tests/list-item-test-1/fail.xml, test/tests/gen/list-item-tests/list-item-test-1/list-item-test-1.sch, test/tests/gen/list-item-tests/list-item-test-1/pass.xml, test/tests/gen/p-punctuation/p-bracket-test/fail.xml, test/tests/gen/p-punctuation/p-bracket-test/p-bracket-test.sch, test/tests/gen/p-punctuation/p-bracket-test/pass.xml, test/tests/gen/rrid-org-code/cell-spacing-test/cell-spacing-test.sch, test/tests/gen/rrid-org-code/code-test/code-test.sch, test/tests/gen/rrid-org-code/diabetes-1-test/diabetes-1-test.sch, test/tests/gen/rrid-org-code/diabetes-2-test/diabetes-2-test.sch, test/tests/gen/rrid-org-code/equal-spacing-test/equal-spacing-test.sch, test/tests/gen/rrid-org-code/org-test/org-test.sch, test/tests/gen/rrid-org-code/ring-diacritic-symbol-test/ring-diacritic-symbol-test.sch, test/tests/gen/rrid-org-code/rrid-test/rrid-test.sch, test/tests/gen/rrid-org-code/unlinked-url/unlinked-url.sch, test/xspec/schematron.sch
- Fix for `list-item-test-1`
- lowercase `sub-article` ids (`dec-letter-reply-test-2`)
- Change to `p-bracket-test`
=> Minor changes

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/department-tests/dept-test-1/dept-test-1.sch, test/tests/gen/department-tests/dept-test-1/fail.xml, test/tests/gen/department-tests/dept-test-1/pass.xml, test/tests/gen/ext-link-tests/ext-link-child-test-4/ext-link-child-test-4.sch, test/tests/gen/ext-link-tests/ext-link-child-test-4/fail.xml, test/tests/gen/ext-link-tests/ext-link-child-test-4/pass.xml, test/tests/gen/supplementary-material-tests/supplementary-material-test-9/fail.xml, test/tests/gen/supplementary-material-tests/supplementary-material-test-9/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add `dept-test-1`, closes #81
- Add `ext-link-child-test-4`, closes #83
=> Add two tests

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/fig-caption-tests/fig-caption-test-1/fail.xml, test/tests/gen/fig-caption-tests/fig-caption-test-1/fig-caption-test-1.sch, test/tests/gen/fig-caption-tests/fig-caption-test-1/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `fig-caption-test-1` closes #86
=> Add fig caption punctuation test

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/doi-conf-ref-checks/conf-doi-test-1/conf-doi-test-1.sch, test/tests/gen/doi-conf-ref-checks/conf-doi-test-1/fail.xml, test/tests/gen/doi-conf-ref-checks/conf-doi-test-1/pass.xml, test/tests/gen/journal-title-tests/zenodo-check/fail.xml, test/tests/gen/journal-title-tests/zenodo-check/pass.xml, test/tests/gen/th-child-tests/th-child-test-2/th-child-test-2.sch, test/tests/gen/unallowed-symbol-tests/plus-minus-presence/fail.xml, test/tests/gen/unallowed-symbol-tests/plus-minus-presence/pass.xml, test/tests/gen/unallowed-symbol-tests/plus-minus-presence/plus-minus-presence.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Allow `inline-graphic` in `th` elements.
- Add `conf-doi-test-1` - closes #92
=> Minor improvements

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/author-aff-tests/final-auth-aff-test-1/fail.xml, test/tests/gen/author-aff-tests/final-auth-aff-test-1/final-auth-aff-test-1.sch, test/tests/gen/author-aff-tests/final-auth-aff-test-1/pass.xml, test/tests/gen/author-aff-tests/final-auth-aff-test-2/fail.xml, test/tests/gen/author-aff-tests/final-auth-aff-test-2/final-auth-aff-test-2.sch, test/tests/gen/author-aff-tests/final-auth-aff-test-2/pass.xml, test/tests/gen/author-aff-tests/final-auth-aff-test-3/fail.xml, test/tests/gen/author-aff-tests/final-auth-aff-test-3/final-auth-aff-test-3.sch, test/tests/gen/author-aff-tests/final-auth-aff-test-3/pass.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-1/fail.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-1/pass.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-1/pre-auth-aff-test-1.sch, test/tests/gen/author-aff-tests/pre-auth-aff-test-2/fail.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-2/pass.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-2/pre-auth-aff-test-2.sch, test/tests/gen/author-aff-tests/pre-auth-aff-test-3/fail.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-3/pass.xml, test/tests/gen/author-aff-tests/pre-auth-aff-test-3/pre-auth-aff-test-3.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch
- Structural conformance for author affiliations
=> Add author aff tests

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/dec-letter-editor-tests-3/dec-letter-editor-test-6/dec-letter-editor-test-6.sch, test/tests/gen/dec-letter-editor-tests-3/dec-letter-editor-test-6/fail.xml, test/tests/gen/dec-letter-editor-tests-3/dec-letter-editor-test-6/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch
- Assert for `senior_editor` roles in sub-article front-stub
=> More sub-article contrib changes

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/journals.xml, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/dec-letter-editor-tests-3/dec-letter-editor-test-6/fail.xml, test/tests/gen/dec-letter-editor-tests-3/dec-letter-editor-test-6/pass.xml, test/tests/gen/doi-journal-ref-checks/journal-doi-test-1/journal-doi-test-1.sch, test/tests/gen/ext-link-tests/url-conformance-test/fail.xml, test/tests/gen/ext-link-tests/url-conformance-test/pass.xml, test/tests/gen/ext-link-tests/url-conformance-test/url-conformance-test.sch, test/tests/gen/ref-xref-conformance/ref-xref-test-27/fail.xml, test/tests/gen/ref-xref-conformance/ref-xref-test-27/pass.xml, test/tests/gen/ref-xref-conformance/ref-xref-test-27/ref-xref-test-27.sch, test/tests/gen/ref-xref-conformance/ref-xref-test-28/fail.xml, test/tests/gen/ref-xref-conformance/ref-xref-test-28/pass.xml, test/tests/gen/ref-xref-conformance/ref-xref-test-28/ref-xref-test-28.sch, test/tests/gen/rrid-org-code/org-test/fail.xml, test/tests/gen/rrid-org-code/org-test/pass.xml, test/xspec/journals.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch
- Updates to Journal DOI tests
- Improve `url-conformance-test` message
- Exclude DAS dataset refs from `org-test`
- Add `ref-xref-test-27` and `ref-xref-test-27`
=> Improvements

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/funders.xml, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/fig-source-code-tests/fig-code-test-2/fail.xml, test/tests/gen/fig-source-code-tests/fig-code-test-2/pass.xml, test/tests/gen/fig-source-data-tests/fig-data-test-2/fail.xml, test/tests/gen/fig-source-data-tests/fig-data-test-2/pass.xml, test/tests/gen/fig-xref-conformance/fig-xref-test-15/fail.xml, test/tests/gen/fig-xref-conformance/fig-xref-test-15/fig-xref-test-15.sch, test/tests/gen/fig-xref-conformance/fig-xref-test-15/pass.xml, test/tests/gen/table-source-code-tests/table-code-test-2/fail.xml, test/tests/gen/table-source-code-tests/table-code-test-2/pass.xml, test/tests/gen/table-source-data-tests/table-data-test-2/fail.xml, test/tests/gen/table-source-data-tests/table-data-test-2/pass.xml, test/xspec/funders.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch, xquery/remove-indistinct-funders.xq
- Add fig link conformance test - `fig-xref-test-15`
- Cleanup funders and fix in query
=> feat: Add figure test

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/orcid-tests/final-orcid-test-3/fail.xml, test/tests/gen/orcid-tests/final-orcid-test-3/final-orcid-test-3.sch, test/tests/gen/orcid-tests/final-orcid-test-3/pass.xml, test/tests/gen/orcid-tests/orcid-test-1/orcid-test-1.sch, test/tests/gen/orcid-tests/pre-orcid-test-3/fail.xml, test/tests/gen/orcid-tests/pre-orcid-test-3/pass.xml, test/tests/gen/orcid-tests/pre-orcid-test-3/pre-orcid-test-3.sch, test/tests/gen/test-title-group/article-title-test-11/article-title-test-11.sch, test/tests/gen/test-title-group/article-title-test-11/fail.xml, test/tests/gen/test-title-group/article-title-test-11/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch
- Add pre and final versions of duplicate ORCiD check.
- Exclude Replication studies from `article-title-test-11`
=> feat: Add duplicate ORCiD test

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/meta-value-tests/pre-custom-meta-test-6/fail.xml, test/tests/gen/meta-value-tests/pre-custom-meta-test-6/pass.xml, test/tests/gen/meta-value-tests/pre-custom-meta-test-6/pre-custom-meta-test-6.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch, validator/webapp/schematron/pre-JATS-schematron.sch
- Re-add pre-author full stop for impact statements - `pre-custom-meta-test-6`.
=> fix: re-add impact statement check

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/schematron.sch, test/tests/gen/colour-styled-content/final-colour-styled-content-check/final-colour-styled-content-check.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/schematron/final-JATS-schematron.sch
- Fix for `final-colour-styled-content-check` - change role from `final` to `error`
=> fix: role error

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml, test/tests/gen/supplementary-material-tests/supplementary-material-test-11/fail.xml, test/tests/gen/supplementary-material-tests/supplementary-material-test-11/pass.xml, test/tests/gen/supplementary-material-tests/supplementary-material-test-11/supplementary-material-test-11.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Warning for downloadable files with a title containing key resource - `supplementary-material-test-11`
=> improvement: Add new check

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/feature-bio-tests/feature-bio-test-1/feature-bio-test-1.sch, test/tests/gen/feature-bio-tests/feature-bio-test-2/fail.xml, test/tests/gen/feature-bio-tests/feature-bio-test-2/feature-bio-test-2.sch, test/tests/gen/feature-bio-tests/feature-bio-test-2/pass.xml, test/tests/gen/feature-bio-tests/feature-bio-test-4/feature-bio-test-4.sch, test/tests/gen/feature-bio-tests/feature-bio-test-5/feature-bio-test-5.sch, test/tests/gen/feature-bio-tests/feature-bio-test-6/fail.xml, test/tests/gen/feature-bio-tests/feature-bio-test-6/feature-bio-test-6.sch, test/tests/gen/feature-bio-tests/feature-bio-test-6/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `bio` conformance for authors with multiple affiliations - `feature-bio-test-6`
=> improvement: Add feature bio check

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/front-permissions-tests/permissions-info/fail.xml, test/tests/gen/front-permissions-tests/permissions-info/pass.xml, test/tests/gen/front-permissions-tests/permissions-info/permissions-info.sch, test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml, test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml, test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml, test/tests/gen/supplementary-material-tests/source-code-test-2/fail.xml, test/tests/gen/supplementary-material-tests/source-code-test-2/pass.xml, test/tests/gen/supplementary-material-tests/source-code-test-2/source-code-test-2.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add warning for source code files which have not been zipped.
- Add info message for licensing for each article
=> improvement: Add more checks

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/ext-link-tests/ftp-credentials-flag/fail.xml, test/tests/gen/ext-link-tests/ftp-credentials-flag/ftp-credentials-flag.sch, test/tests/gen/ext-link-tests/ftp-credentials-flag/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `ftp-credentials-flag` - fire a warning for any FTP links that contain credentials
=> improvement: warning for FTP links w/ credentials

src/final-JATS-schematron.sch, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/schematron.sch, test/tests/gen/fig-panel-tests/fig-panel-test-1/fail.xml, test/tests/gen/fig-panel-tests/fig-panel-test-1/fig-panel-test-1.sch, test/tests/gen/fig-panel-tests/fig-panel-test-1/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `fig-panel-test-1` - punctuation in bold elements in fig captions
=> improvement: Add fig panel test

src/dl-schematron.sch, src/dl-schematron.xsl, src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/xspec/schematron.sch, validator/webapp/validator.xqm, xquery/elife.xqm, xquery/refactor.xq
- Add decision letter specific schematron for new workflow
- Polite http requests to Glencoe in validator
=> improvement: add decision letter schematron

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/digest-tests/final-digest-test-2/fail.xml, test/tests/gen/digest-tests/final-digest-test-2/final-digest-test-2.sch, test/tests/gen/digest-tests/final-digest-test-2/pass.xml, test/tests/gen/feature-comment-tests/final-feat-ok-test/fail.xml, test/tests/gen/feature-comment-tests/final-feat-ok-test/final-feat-ok-test.sch, test/tests/gen/feature-comment-tests/final-feat-ok-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, validator/webapp/validator.xqm
- Check for presence of queries in the text from features, such as [OK?]
=> improvement: add feature check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/given-names-tests/final-given-names-test-16/fail.xml, test/tests/gen/given-names-tests/final-given-names-test-16/final-given-names-test-16.sch, test/tests/gen/given-names-tests/final-given-names-test-16/pass.xml, test/tests/gen/given-names-tests/pre-given-names-test-16/fail.xml, test/tests/gen/given-names-tests/pre-given-names-test-16/pass.xml, test/tests/gen/given-names-tests/pre-given-names-test-16/pre-given-names-test-16.sch, test/tests/gen/surname-tests/surname-test-9/fail.xml, test/tests/gen/surname-tests/surname-test-9/pass.xml, test/tests/gen/surname-tests/surname-test-9/surname-test-9.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Fire warnings for given-names and surname containing brackets
=> improvement: add bracket name checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/KRT-td-checks/addgene-test/addgene-test.sch, test/tests/gen/KRT-td-checks/addgene-test/fail.xml, test/tests/gen/KRT-td-checks/addgene-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Check for `addgene # 0000` or similar in KR table so that these can be changed to RRIDs with appropriate links.
=> improvement: addgene check

src/dl-schematron.xsl, src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/decision-missing-table-tests/decision-missing-table-test/decision-missing-table-test.sch, test/tests/gen/decision-missing-table-tests/decision-missing-table-test/fail.xml, test/tests/gen/decision-missing-table-tests/decision-missing-table-test/pass.xml, test/tests/gen/disp-quote-tests/disp-quote-test-1/disp-quote-test-1.sch, test/tests/gen/disp-quote-tests/disp-quote-test-2/disp-quote-test-2.sch, test/tests/gen/reply-missing-table-tests/reply-missing-table-test/fail.xml, test/tests/gen/reply-missing-table-tests/reply-missing-table-test/pass.xml, test/tests/gen/reply-missing-table-tests/reply-missing-table-test/reply-missing-table-test.sch, test/tests/gen/sub-article-ext-link-tests/paper-pile-test/fail.xml, test/tests/gen/sub-article-ext-link-tests/paper-pile-test/paper-pile-test.sch, test/tests/gen/sub-article-ext-link-tests/paper-pile-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add warning for possible missing table labels.
- Add error for paperpile links.
=> improvement: add sub-article checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-6/fail.xml, test/tests/gen/auth-kwd-style/auth-kwd-check-6/pass.xml, test/tests/gen/permissions-2/fig-permissions-test-12/fail.xml, test/tests/gen/permissions-2/fig-permissions-test-12/fig-permissions-test-12.sch, test/tests/gen/permissions-2/fig-permissions-test-12/pass.xml, test/tests/gen/rrid-org-code/final-missing-url-test/fail.xml, test/tests/gen/rrid-org-code/final-missing-url-test/final-missing-url-test.sch, test/tests/gen/rrid-org-code/final-missing-url-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Permit pluralised version of text in `fig-permissions-test-12`
- Fix message text in `auth-kwd-check-6`
- Add `final-missing-url-test`
=> fix: minor fixes

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-6/auth-kwd-check-6.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-6/fail.xml, test/tests/gen/auth-kwd-style/auth-kwd-check-6/pass.xml, test/xspec/schematron.sch
- Only fire `auth-kwd-check-6` if keyword is > 4 words
=> fix: up limit for auth-kwd-check-6

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/das-elem-citation-data-pub-id/final-das-pub-id-2/fail.xml, test/tests/gen/das-elem-citation-data-pub-id/final-das-pub-id-2/final-das-pub-id-2.sch, test/tests/gen/das-elem-citation-data-pub-id/final-das-pub-id-2/pass.xml, test/tests/gen/das-elem-citation-data-pub-id/pre-das-pub-id-2/fail.xml, test/tests/gen/das-elem-citation-data-pub-id/pre-das-pub-id-2/pass.xml, test/tests/gen/das-elem-citation-data-pub-id/pre-das-pub-id-2/pre-das-pub-id-2.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Split `pub-id-2` into pre and final versions
=> improvement: split pub-id-2

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/elem-citation-gen-name-4/err-elem-cit-gen-name-4/err-elem-cit-gen-name-4.sch, test/tests/gen/elem-citation-gen-name-4/err-elem-cit-gen-name-4/fail.xml, test/tests/gen/elem-citation-gen-name-4/err-elem-cit-gen-name-4/pass.xml, test/tests/gen/suffix-tests/suffix-assert/fail.xml, test/tests/gen/suffix-tests/suffix-assert/pass.xml, test/tests/gen/suffix-tests/suffix-assert/suffix-assert.sch, test/xspec/schematron.sch
- Permit `Jr` and `Sr` in suffix.
=> fix: permit more suffix values

src/dl-schematron.sch, src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/covid-prologue/covid-processing-instruction/covid-processing-instruction.sch, test/tests/gen/covid-prologue/covid-processing-instruction/fail.xml, test/tests/gen/covid-prologue/covid-processing-instruction/pass.xml, test/tests/gen/elem-citation-journal-fpage/err-elem-cit-journal-6-6/fail.xml, test/tests/gen/elem-citation-journal-fpage/err-elem-cit-journal-6-6/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec, xquery/elife.xqm
- Add check for presence of pmc covid procesing instruction if article title suggests its covid related
- Fix for `err-elem-cit-journal-6-6`
=> improvement: Add covid processing-instruction check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/data-availability-p/final-das-p-conformity-1/fail.xml, test/tests/gen/data-availability-p/final-das-p-conformity-1/final-das-p-conformity-1.sch, test/tests/gen/data-availability-p/final-das-p-conformity-1/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Ensure all `<p>`s in the data availability statement contain content.
=> improvement: add das check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/data-availability-p/final-das-p-conformity-1/fail.xml, test/tests/gen/data-availability-p/final-das-p-conformity-1/pass.xml, test/tests/gen/element-citation-descendants/tagging-elem-cit-des/fail.xml, test/tests/gen/element-citation-descendants/tagging-elem-cit-des/pass.xml, test/tests/gen/element-citation-descendants/tagging-elem-cit-des/tagging-elem-cit-des.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Error for tagging such as `<em>` in references.
=> improvement: add tagging as text check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/element-citation-descendants/tagging-elem-cit-des/fail.xml, test/tests/gen/element-citation-descendants/tagging-elem-cit-des/pass.xml, test/tests/gen/review-article-title-tests/review-article-title-1/fail.xml, test/tests/gen/review-article-title-tests/review-article-title-1/pass.xml, test/tests/gen/review-article-title-tests/review-article-title-1/review-article-title-1.sch, test/tests/gen/review-article-title-tests/review-article-title-2/fail.xml, test/tests/gen/review-article-title-tests/review-article-title-2/pass.xml, test/tests/gen/review-article-title-tests/review-article-title-2/review-article-title-2.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add checks for review article titles
=> improvement: review article checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/ext-link-tests-2/ext-link-length/ext-link-length.sch, test/tests/gen/ext-link-tests-2/ext-link-length/fail.xml, test/tests/gen/ext-link-tests-2/ext-link-length/pass.xml, test/tests/gen/ext-link-tests/ext-link-text/ext-link-text.sch, test/tests/gen/ext-link-tests/ext-link-text/fail.xml, test/tests/gen/ext-link-tests/ext-link-text/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Info for long url text
- Warning for text and embedded link mismatch
=> Improvement: add url checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/fig-source-code-tests/fig-code-id/fail.xml, test/tests/gen/fig-source-code-tests/fig-code-id/fig-code-id.sch, test/tests/gen/fig-source-code-tests/fig-code-id/pass.xml, test/tests/gen/fig-source-data-tests/fig-data-id/fail.xml, test/tests/gen/fig-source-data-tests/fig-data-id/fig-data-id.sch, test/tests/gen/fig-source-data-tests/fig-data-id/pass.xml, test/tests/gen/table-source-code-tests/table-code-id/fail.xml, test/tests/gen/table-source-code-tests/table-code-id/pass.xml, test/tests/gen/table-source-code-tests/table-code-id/table-code-id.sch, test/tests/gen/table-source-data-tests/table-data-id/fail.xml, test/tests/gen/table-source-data-tests/table-data-id/pass.xml, test/tests/gen/table-source-data-tests/table-data-id/table-data-id.sch, test/tests/gen/vid-source-code-tests/vid-code-id/fail.xml, test/tests/gen/vid-source-code-tests/vid-code-id/pass.xml, test/tests/gen/vid-source-code-tests/vid-code-id/vid-code-id.sch, test/tests/gen/vid-source-data-tests/vid-data-id/fail.xml, test/tests/gen/vid-source-data-tests/vid-data-id/pass.xml, test/tests/gen/vid-source-data-tests/vid-data-id/vid-data-id.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add tests for asset level source data and code ids.
=> fix: asset source data id conformance

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/given-names-tests/given-names-test-15/given-names-test-15.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Downgrade given-names-test-15 to info, pending discussion about Pubmed.
=> fix: downgrade given-names-test-15

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/software-heritage-tests/software-heritage-test-1/software-heritage-test-1.sch, test/tests/gen/software-heritage-tests/software-heritage-test-3/software-heritage-test-3.sch, test/tests/gen/software-heritage-tests/software-heritage-test-4/fail.xml, test/tests/gen/software-heritage-tests/software-heritage-test-4/pass.xml, test/tests/gen/software-heritage-tests/software-heritage-test-4/software-heritage-test-4.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- `software-heritage-test-4` - check that origin in SH link is the same as a preceding `ext-link`.
=> Add new SH test

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/software-heritage-tests/software-heritage-test-5/fail.xml, test/tests/gen/software-heritage-tests/software-heritage-test-5/pass.xml, test/tests/gen/software-heritage-tests/software-heritage-test-5/software-heritage-test-5.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Another conformance check for SWH links.
=> Add SWH test

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/additional-info-tests/additional-info-test-1/additional-info-test-1.sch, test/tests/gen/additional-info-tests/additional-info-test-2/additional-info-test-2.sch, test/tests/gen/additional-info-tests/additional-info-test-4/additional-info-test-4.sch, test/tests/gen/additional-info-tests/final-additional-info-test-3/fail.xml, test/tests/gen/additional-info-tests/final-additional-info-test-3/final-additional-info-test-3.sch, test/tests/gen/additional-info-tests/final-additional-info-test-3/pass.xml, test/tests/gen/additional-info-tests/pre-additional-info-test-3/fail.xml, test/tests/gen/additional-info-tests/pre-additional-info-test-3/pass.xml, test/tests/gen/additional-info-tests/pre-additional-info-test-3/pre-additional-info-test-3.sch, test/tests/gen/auth-cont-tests/auth-cont-test-1/auth-cont-test-1.sch, test/tests/gen/auth-cont-tests/auth-cont-test-1/fail.xml, test/tests/gen/auth-cont-tests/auth-cont-test-1/pass.xml, test/tests/gen/collab-cont-tests/collab-cont-test-1/collab-cont-test-1.sch, test/tests/gen/collab-cont-tests/collab-cont-test-1/fail.xml, test/tests/gen/collab-cont-tests/collab-cont-test-1/pass.xml, test/xspec/schematron.sch
- Review articles now follow research articles for author contributions.
=> Review article contributions

src/dl-schematron.xsl, src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-1/dec-letter-box-test-1.sch, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-1/fail.xml, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-1/pass.xml, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-2/dec-letter-box-test-2.sch, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-2/fail.xml, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-2/pass.xml, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-3/dec-letter-box-test-3.sch, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-3/fail.xml, test/tests/gen/dec-letter-box-tests/dec-letter-box-test-3/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Checks for the boilerplate text at the top of decision letters.
=> Add decision letter checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/given-names-tests/given-names-test-5/fail.xml, test/tests/gen/given-names-tests/given-names-test-5/pass.xml, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-6/fail.xml, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-6/pass.xml, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-6/supp-file-xref-conformity-6.sch, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-7/fail.xml, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-7/pass.xml, test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-7/supp-file-xref-conformity-7.sch, test/tests/gen/surname-tests/surname-test-4/fail.xml, test/tests/gen/surname-tests/surname-test-4/pass.xml, test/tests/gen/surname-tests/surname-test-4/surname-test-4.sch, test/tests/gen/test-title-group/article-title-test-10/article-title-test-10.sch, test/tests/gen/test-title-group/article-title-test-10/fail.xml, test/tests/gen/test-title-group/article-title-test-10/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Fix for `given-names-test-5` and `surname-test-4`.
- Add source data and code xref tests - `supp-file-xref-conformity-6`, `supp-file-xref-conformity-7`.
=> new checks and fix

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/medicine-abstract-conformance.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Downgrade `medicine-abstract-conformance` to warning temporarily.
=> downgrade medicine-abstract-conformance

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/article-tests/line-count/line-count.sch, test/tests/gen/code-tests-2/code-sibling-test/code-sibling-test.sch, test/tests/gen/code-tests-3/code-sibling-test-2/code-sibling-test-2.sch, test/tests/gen/code-tests/code-child-test/code-child-test.sch, test/tests/gen/code-tests/code-parent-test/code-parent-test.sch, test/tests/gen/rrid-org-code/code-test/code-test.sch, test/tests/gen/table-source-data-tests/table-data-test-2/table-data-test-2.sch, test/xspec/schematron.sch
Add GitBook links for "code" checks. closes elifesciences/schematron-gitbook#33
=> Add GitBook links

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/ext-link-tests/url-conformance-test/fail.xml, test/tests/gen/ext-link-tests/url-conformance-test/pass.xml, test/tests/gen/ext-link-tests/url-conformance-test/url-conformance-test.sch, test/tests/gen/medicine-abstract-tests-2/medicine-abstract-conformance-2/fail.xml, test/tests/gen/medicine-abstract-tests-2/medicine-abstract-conformance-2/medicine-abstract-conformance-2.sch, test/tests/gen/medicine-abstract-tests-2/medicine-abstract-conformance-2/pass.xml, test/tests/gen/medicine-section-tests/medicine-discussion/fail.xml, test/tests/gen/medicine-section-tests/medicine-discussion/medicine-discussion.sch, test/tests/gen/medicine-section-tests/medicine-discussion/pass.xml, test/tests/gen/medicine-section-tests/medicine-methods/fail.xml, test/tests/gen/medicine-section-tests/medicine-methods/medicine-methods.sch, test/tests/gen/medicine-section-tests/medicine-methods/pass.xml, test/tests/gen/medicine-section-tests/medicine-results/fail.xml, test/tests/gen/medicine-section-tests/medicine-results/medicine-results.sch, test/tests/gen/medicine-section-tests/medicine-results/pass.xml, test/tests/gen/software-heritage-tests/software-heritage-test-1/software-heritage-test-1.sch, test/tests/gen/software-heritage-tests/software-heritage-test-2/software-heritage-test-2.sch, test/tests/gen/software-heritage-tests/software-heritage-test-3/software-heritage-test-3.sch, test/tests/gen/software-heritage-tests/software-heritage-test-4/fail.xml, test/tests/gen/software-heritage-tests/software-heritage-test-4/pass.xml, test/tests/gen/software-heritage-tests/software-heritage-test-4/software-heritage-test-4.sch, test/tests/gen/software-heritage-tests/software-heritage-test-5/software-heritage-test-5.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
Medicine structure tests now warnings because of exceptions
=> fix: downgrade medicine structure checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/app-box-tests/app-box-label-test-2/app-box-label-test-2.sch, test/tests/gen/app-box-tests/app-box-label-test-2/fail.xml, test/tests/gen/app-box-tests/app-box-label-test-2/pass.xml, test/tests/gen/app-box-tests/app-box-label-test/app-box-label-test.sch, test/tests/gen/app-box-tests/app-box-label-test/fail.xml, test/tests/gen/app-box-tests/app-box-label-test/pass.xml, test/tests/gen/body-box-tests/body-box-label-test/body-box-label-test.sch, test/tests/gen/body-box-tests/body-box-label-test/fail.xml, test/tests/gen/body-box-tests/body-box-label-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
=> fix: add box label tests

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/app-box-tests/app-box-label-test-2/fail.xml, test/tests/gen/app-box-tests/app-box-label-test-2/pass.xml, test/tests/gen/app-box-tests/app-box-label-test/app-box-label-test.sch, test/tests/gen/app-box-tests/app-box-label-test/fail.xml, test/tests/gen/app-box-tests/app-box-label-test/pass.xml, test/tests/gen/app-content-tests/app-little-content/app-little-content.sch, test/tests/gen/app-content-tests/app-little-content/fail.xml, test/tests/gen/app-content-tests/app-little-content/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- fix for `app-box-tests`.
- add `app-little-content`
=> fix and add appendix test

src/final-package-JATS-schematron.sch, src/schematron.sch, test/tests/gen/final-package/graphic-media-presence/fail.xml, test/tests/gen/final-package/graphic-media-presence/graphic-media-presence.sch, test/tests/gen/final-package/graphic-media-presence/pass.xml, test/tests/gen/license-ali-ref-link-tests/license-p-test-4/fail.xml, test/tests/gen/license-ali-ref-link-tests/license-p-test-4/pass.xml, test/tests/gen/license-link-tests/license-p-test-3/fail.xml, test/tests/gen/license-link-tests/license-p-test-3/pass.xml
- Ignore preprint `self-uri` in java file checks
=> fix: final package checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/elem-citation/self-cite-1/fail.xml, test/tests/gen/elem-citation/self-cite-1/pass.xml, test/tests/gen/elem-citation/self-cite-1/self-cite-1.sch, test/tests/gen/elem-citation/self-cite-2/fail.xml, test/tests/gen/elem-citation/self-cite-2/pass.xml, test/tests/gen/feature-comment-tests/final-feat-query-test/final-feat-query-test.sch, test/tests/gen/related-articles-conformance/related-articles-test-6/fail.xml, test/tests/gen/related-articles-conformance/related-articles-test-6/pass.xml, test/tests/gen/related-articles-conformance/related-articles-test-6/related-articles-test-6.sch, test/tests/gen/video-test/final-video-title-sa/fail.xml, test/tests/gen/video-test/final-video-title-sa/final-video-title-sa.sch, test/tests/gen/video-test/final-video-title-sa/pass.xml, test/tests/gen/video-test/final-video-title/fail.xml, test/tests/gen/video-test/final-video-title/final-video-title.sch, test/tests/gen/video-test/final-video-title/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Ignore sub-article videos for title checks
- ignore casing in `related-articles-test-6`
- fix typos in messages
- Add GitBook links, closes elifesciences/schematron-gitbook#119
=> chore: various edits

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/das-software-heritage-tests/software-heritage-test-1/fail.xml, test/tests/gen/das-software-heritage-tests/software-heritage-test-1/pass.xml, test/tests/gen/das-software-heritage-tests/software-heritage-test-1/software-heritage-test-1.sch, test/tests/gen/missing-ref-cited/missing-file-in-text-test/fail.xml, test/tests/gen/missing-ref-cited/missing-file-in-text-test/missing-file-in-text-test.sch, test/tests/gen/missing-ref-cited/missing-file-in-text-test/pass.xml, test/xspec/schematron.sch
- do not permit just reision SWH link in `software-heritage-test-1`
- Add `missing-file-in-text-test`
=> chore: add and revise check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-8/auth-kwd-check-8.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-8/fail.xml, test/tests/gen/auth-kwd-style/auth-kwd-check-8/pass.xml, test/tests/gen/auth-kwd-style/auth-kwd-check-9/auth-kwd-check-9.sch, test/tests/gen/auth-kwd-style/auth-kwd-check-9/fail.xml, test/tests/gen/auth-kwd-style/auth-kwd-check-9/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add further checks for author keywords
=> chore: minor update

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/data-availability-extra-p/das-extra-p/das-extra-p.sch, test/tests/gen/data-availability-extra-p/das-extra-p/fail.xml, test/tests/gen/data-availability-extra-p/das-extra-p/pass.xml, test/tests/gen/data-availability-generated-p/das-generated-p-1/das-generated-p-1.sch, test/tests/gen/data-availability-generated-p/das-generated-p-1/fail.xml, test/tests/gen/data-availability-generated-p/das-generated-p-1/pass.xml, test/tests/gen/data-availability-generated-p/das-generated-p-2/das-generated-p-2.sch, test/tests/gen/data-availability-generated-p/das-generated-p-2/fail.xml, test/tests/gen/data-availability-generated-p/das-generated-p-2/pass.xml, test/tests/gen/data-availability-used-p/das-used-p-1/das-used-p-1.sch, test/tests/gen/data-availability-used-p/das-used-p-1/fail.xml, test/tests/gen/data-availability-used-p/das-used-p-1/pass.xml, test/tests/gen/data-availability-used-p/das-used-p-2/das-used-p-2.sch, test/tests/gen/data-availability-used-p/das-used-p-2/fail.xml, test/tests/gen/data-availability-used-p/das-used-p-2/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Checks for ps in data availability section
=> chore: new checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/data-content-tests/data-gen-p-presence/data-gen-p-presence.sch, test/tests/gen/data-content-tests/data-gen-p-presence/fail.xml, test/tests/gen/data-content-tests/data-gen-p-presence/pass.xml, test/tests/gen/data-content-tests/data-used-p-presence/data-used-p-presence.sch, test/tests/gen/data-content-tests/data-used-p-presence/fail.xml, test/tests/gen/data-content-tests/data-used-p-presence/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Error for duplicated used/generated sentences in DAS.
=> chore: add DAS check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/ncbi-pub-id-checks/ncbi-pub-id-1/fail.xml, test/tests/gen/ncbi-pub-id-checks/ncbi-pub-id-1/ncbi-pub-id-1.sch, test/tests/gen/ncbi-pub-id-checks/ncbi-pub-id-1/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- fire warning for NCBI dataset links that do not contain accession number
=> chore: add new data ref check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/math-overset-tests/math-overset-bar-test/fail.xml, test/tests/gen/math-overset-tests/math-overset-bar-test/math-overset-bar-test.sch, test/tests/gen/math-overset-tests/math-overset-bar-test/pass.xml, test/tests/gen/math-overset-tests/math-overset-missing-test/fail.xml, test/tests/gen/math-overset-tests/math-overset-missing-test/math-overset-missing-test.sch, test/tests/gen/math-overset-tests/math-overset-missing-test/pass.xml, test/tests/gen/preprint-title-tests/not-rxiv-test/fail.xml, test/tests/gen/preprint-title-tests/not-rxiv-test/pass.xml, test/tests/gen/preprint-title-tests/osfpreprints-test/fail.xml, test/tests/gen/preprint-title-tests/osfpreprints-test/osfpreprints-test.sch, test/tests/gen/preprint-title-tests/osfpreprints-test/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Add osf preprints check
- Add overset math checks
=> chore: minor updates

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/table-xref-conformance/table-xref-conformity-1/fail.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-1/pass.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-1/table-xref-conformity-1.sch, test/tests/gen/table-xref-conformance/table-xref-conformity-2/table-xref-conformity-2.sch, test/tests/gen/table-xref-conformance/table-xref-conformity-3/fail.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-3/pass.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-3/table-xref-conformity-3.sch, test/tests/gen/table-xref-conformance/table-xref-conformity-4/table-xref-conformity-4.sch, test/tests/gen/table-xref-conformance/table-xref-conformity-5/fail.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-5/pass.xml, test/tests/gen/table-xref-conformance/table-xref-conformity-5/table-xref-conformity-5.sch, test/tests/gen/table-xref-conformance/table-xref-test-1/table-xref-test-1.sch, test/tests/gen/table-xref-conformance/table-xref-test-2/table-xref-test-2.sch, test/tests/gen/table-xref-conformance/table-xref-test-4/table-xref-test-4.sch, test/tests/gen/table-xref-conformance/table-xref-test-5/table-xref-test-5.sch, test/tests/gen/table-xref-conformance/table-xref-test-6/table-xref-test-6.sch, test/tests/gen/wellcome-fund-statement-tests/wellcome-fund-statement/fail.xml, test/tests/gen/wellcome-fund-statement-tests/wellcome-fund-statement/pass.xml, test/tests/gen/wellcome-fund-statement-tests/wellcome-fund-statement/wellcome-fund-statement.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Don't fire warnings for latest citation style.
- Add Wellcome funding check
=> chore: minor edits

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/permissions-3a/block-permish-ali-license/block-permish-ali-license.sch, test/tests/gen/permissions-3a/block-permish-ali-license/fail.xml, test/tests/gen/permissions-3a/block-permish-ali-license/pass.xml, test/tests/gen/permissions-3b/block-permish-license-p-link/block-permish-license-p-link.sch, test/tests/gen/permissions-3b/block-permish-license-p-link/fail.xml, test/tests/gen/permissions-3b/block-permish-license-p-link/pass.xml, test/tests/gen/permissions-3c/block-permish-license-link/block-permish-license-link.sch, test/tests/gen/permissions-3c/block-permish-license-link/fail.xml, test/tests/gen/permissions-3c/block-permish-license-link/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Fire errors for block level permissions containing links which are the same as the article.
=> chore: add permissions checks

src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/italic-house-style/pre-a-posteriori-italic-test/pre-a-posteriori-italic-test.sch, test/tests/gen/italic-house-style/pre-a-priori-italic-test/pre-a-priori-italic-test.sch, test/tests/gen/italic-house-style/pre-ad-libitum-italic-test/pre-ad-libitum-italic-test.sch, test/tests/gen/italic-house-style/pre-de-novo-italic-test/pre-de-novo-italic-test.sch, test/tests/gen/italic-house-style/pre-et-al-italic-test/pre-et-al-italic-test.sch, test/tests/gen/italic-house-style/pre-ex-vivo-italic-test/pre-ex-vivo-italic-test.sch, test/tests/gen/italic-house-style/pre-in-natura-italic-test/pre-in-natura-italic-test.sch, test/tests/gen/italic-house-style/pre-in-ovo-italic-test/pre-in-ovo-italic-test.sch, test/tests/gen/italic-house-style/pre-in-planta-italic-test/pre-in-planta-italic-test.sch, test/tests/gen/italic-house-style/pre-in-situ-italic-test/pre-in-situ-italic-test.sch, test/tests/gen/italic-house-style/pre-in-utero-italic-test/pre-in-utero-italic-test.sch, test/tests/gen/italic-house-style/pre-in-vitro-italic-test/pre-in-vitro-italic-test.sch, test/tests/gen/italic-house-style/pre-in-vivo-italic-test/pre-in-vivo-italic-test.sch, test/tests/gen/italic-house-style/pre-nomen-novum-italic-test/pre-nomen-novum-italic-test.sch, test/tests/gen/italic-house-style/pre-rete-mirabile-italic-test/pre-rete-mirabile-italic-test.sch, test/tests/gen/italic-house-style/pre-sensu-italic-test/pre-sensu-italic-test.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Italic house style checks downgraded to warning in pre version
=> chore: downgrade italic house style checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/abstract-tests/abstract-test-9/abstract-test-9.sch, test/tests/gen/abstract-tests/abstract-test-9/fail.xml, test/tests/gen/abstract-tests/abstract-test-9/pass.xml, test/tests/gen/multi-par-tests/multi-par-test-1/fail.xml, test/tests/gen/multi-par-tests/multi-par-test-1/multi-par-test-1.sch, test/tests/gen/multi-par-tests/multi-par-test-1/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Adds `abstract-test-9` and `multi-par-test-1`
=> chore: checks for underscores and dupe names in funding

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/link-ref-tests/doi-in-display-test/doi-in-display-test.sch, test/tests/gen/link-ref-tests/duplicated-content/duplicated-content.sch, test/tests/gen/link-ref-tests/duplicated-content/fail.xml, test/tests/gen/link-ref-tests/duplicated-content/pass.xml, test/tests/gen/link-ref-tests/link-in-display-test/link-in-display-test.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Check for duplicated content in certain reference fields.
=> chore: add check

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/app-fig-pos-tests/final-app-fig-pos-test/fail.xml, test/tests/gen/app-fig-pos-tests/final-app-fig-pos-test/final-app-fig-pos-test.sch, test/tests/gen/app-fig-pos-tests/final-app-fig-pos-test/pass.xml, test/tests/gen/app-fig-pos-tests/pre-app-fig-pos-test/fail.xml, test/tests/gen/app-fig-pos-tests/pre-app-fig-pos-test/pass.xml, test/tests/gen/app-fig-pos-tests/pre-app-fig-pos-test/pre-app-fig-pos-test.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Downgrade `final-award-group-test-7` to warning
- Add appendix figure position checks
=> chore: minor changes

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/elocation-id-tests/test-elocation-conformance-prc/fail.xml, test/tests/gen/elocation-id-tests/test-elocation-conformance-prc/pass.xml, test/tests/gen/elocation-id-tests/test-elocation-conformance-prc/test-elocation-conformance-prc.sch, test/tests/gen/elocation-id-tests/test-elocation-conformance/fail.xml, test/tests/gen/elocation-id-tests/test-elocation-conformance/pass.xml, test/tests/gen/elocation-id-tests/test-elocation-conformance/test-elocation-conformance.sch, test/tests/gen/event-desc-tests/event-desc-content-2/fail.xml, test/tests/gen/event-desc-tests/event-desc-content-2/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- new PRC elocation-id check
- refine volume check for PRC use-case
=> chore: more PRC changes

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/event-desc-tests/event-desc-content-2/fail.xml, test/tests/gen/event-desc-tests/event-desc-content-2/pass.xml, test/tests/gen/journal-title-tests/journal-bracket-check/journal-bracket-check.sch, test/tests/gen/link-ref-tests/duplicated-content/duplicated-content.sch, test/tests/gen/ref-article-title-tests/article-title-case/article-title-case.sch, test/xspec/schematron.sch
Closes elifesciences/schematron-gitbook#206
Closes elifesciences/schematron-gitbook#203
=> chore: add Slab links

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/event-desc-tests/event-desc-content-2/fail.xml, test/tests/gen/event-desc-tests/event-desc-content-2/pass.xml, test/tests/gen/journal-tests/elife-ref-check/elife-ref-check.sch, test/tests/gen/journal-tests/elife-ref-check/fail.xml, test/tests/gen/journal-tests/elife-ref-check/pass.xml, test/tests/gen/related-articles-conformance/related-articles-test-6/fail.xml, test/tests/gen/related-articles-conformance/related-articles-test-6/pass.xml, test/tests/gen/related-articles-conformance/related-articles-test-6/related-articles-test-6.sch, test/tests/gen/test-article-metadata/test-article-id/fail.xml, test/tests/gen/test-article-metadata/test-article-id/pass.xml, test/tests/gen/test-article-metadata/test-article-id/test-article-id.sch, test/tests/gen/test-article-metadata/test-self-uri-pdf-2/fail.xml, test/tests/gen/test-article-metadata/test-self-uri-pdf-2/pass.xml, test/tests/gen/test-article-metadata/test-self-uri-pdf-2/test-self-uri-pdf-2.sch, test/xspec/schematron.sch
As noted in elifesciences/issues#7991
=> chore: permit 5 or 6 digit article ids

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/event-desc-tests/event-desc-content-2/fail.xml, test/tests/gen/event-desc-tests/event-desc-content-2/pass.xml, test/tests/gen/xref-target-tests/table-fn-xref-target-test/table-fn-xref-target-test.sch, test/xspec/schematron.sch
closes elifesciences/schematron-wiki#174
=> chore: add Slab link to table-fn-xref-target-test

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/article-title-tests/absolute-title-length-restriction/absolute-title-length-restriction.sch, test/tests/gen/article-title-tests/absolute-title-length-restriction/fail.xml, test/tests/gen/article-title-tests/absolute-title-length-restriction/pass.xml, test/tests/gen/article-title-tests/final-title-length-restriction/fail.xml, test/tests/gen/article-title-tests/final-title-length-restriction/final-title-length-restriction.sch, test/tests/gen/article-title-tests/final-title-length-restriction/pass.xml, test/tests/gen/article-title-tests/pre-title-length-restriction/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Only fire 140 article title limit for those that are old model
- Add 256 character limit for all article titles
=> Make changes to title checks

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/event-self-uri-tests/event-self-uri-content-type/event-self-uri-content-type.sch, test/tests/gen/event-self-uri-tests/event-self-uri-content/event-self-uri-content.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-1/event-self-uri-href-1.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-2/event-self-uri-href-2.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-3/event-self-uri-href-3.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-4/pass.xml, test/tests/gen/event-self-uri-tests/event-self-uri-href-5/event-self-uri-href-5.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-6/event-self-uri-href-6.sch, test/tests/gen/event-self-uri-tests/event-self-uri-href-6/fail.xml, test/tests/gen/event-self-uri-tests/event-self-uri-href-6/pass.xml, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-1/fail.xml, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-1/pass.xml, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-1/sub-article-doi-check-1.sch, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-2/fail.xml, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-2/pass.xml, test/tests/gen/sub-article-doi-checks/sub-article-doi-check-2/sub-article-doi-check-2.sch, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Version DOIs must ends with a digit between 1 and 9
- Version DOIs must contain the article id.
=> Extra checks on version DOIs

src/rp-schematron-base.sch, src/rp-schematron.sch, src/rp-schematron.xsl, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-1/ed-report-bold-terms-1.sch, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-1/fail.xml, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-1/pass.xml, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-2/ed-report-bold-terms-2.sch, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-2/fail.xml, test/tests/rp/ed-report-bold-terms/ed-report-bold-terms-2/pass.xml, test/tests/rp/ed-report-front-stub/ed-report-sig-kwd-presence/ed-report-sig-kwd-presence.sch, test/tests/rp/ed-report-front-stub/ed-report-sig-kwd-presence/fail.xml, test/tests/rp/ed-report-front-stub/ed-report-sig-kwd-presence/pass.xml, test/tests/rp/ed-report-front-stub/ed-report-str-kwd-presence/ed-report-str-kwd-presence.sch, test/tests/rp/ed-report-front-stub/ed-report-str-kwd-presence/fail.xml, test/tests/rp/ed-report-front-stub/ed-report-str-kwd-presence/pass.xml, test/xspec/rp-schematron.sch, test/xspec/rp-schematron.xspec
- warning for no strength or significance keyword group in the assessment
- error for no matching keyword for a bold term in the assessment content
- error for bold text in the assessment which is not a vocab term
=> RP - add more assessment vocab checks

src/dl-schematron.sch, src/dl-schematron.xsl, src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-2/ed-eval-front-test-2.sch, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-2/fail.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-2/pass.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-3/fail.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-3/pass.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-4/ed-eval-front-test-4.sch, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-4/fail.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-4/pass.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-5/ed-eval-front-test-5.sch, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-5/fail.xml, test/tests/gen/ed-eval-front-tests/ed-eval-front-test-5/pass.xml, test/tests/gen/ed-eval-title-tests/ed-eval-title-test/ed-eval-title-test.sch, test/tests/gen/ed-eval-title-tests/ed-eval-title-test/fail.xml, test/tests/gen/ed-eval-title-tests/ed-eval-title-test/pass.xml, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-1/ed-report-bold-terms-1.sch, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-1/fail.xml, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-1/pass.xml, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-2/ed-report-bold-terms-2.sch, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-2/fail.xml, test/tests/gen/ed-report-bold-terms/ed-report-bold-terms-2/pass.xml, test/xspec/schematron.sch, test/xspec/schematron.xspec
- Permit `eLife Assessment` title
- Add error for missing strength kwd-group
- Add warning for missing significance kwd-group
- Add errors for bolded terms in body of assessment not matching keywords
=> VOR - Assessment changes

src/preprint-changes.xsl
- includes authors in sub-articles
=> RP XSL - remove full stops from all authors

src/rp-schematron-base.sch, src/rp-schematron.sch, src/rp-schematron.xsl, test/tests/rp/sub-article-title-checks/sub-article-title-check-1/fail.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-1/pass.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-1/sub-article-title-check-1.sch, test/tests/rp/sub-article-title-checks/sub-article-title-check-2/fail.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-2/pass.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-2/sub-article-title-check-2.sch, test/tests/rp/sub-article-title-checks/sub-article-title-check-3/fail.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-3/pass.xml, test/tests/rp/sub-article-title-checks/sub-article-title-check-3/sub-article-title-check-3.sch, test/xspec/rp-schematron.sch, test/xspec/rp-schematron.xspec
Permit only certain titles, depending on the article-type for that sub-article
=> RP - add sub-article title checks

src/preprint-changes.xsl, test/tests/preprint-changes/ack-title/output.xml, test/tests/preprint-changes/all/output.xml, test/tests/preprint-changes/rearrange-back/output.xml, test/tests/preprint-changes/strip-sc/output.xml
update template to fix ack title to always use UK spelling
=> RP XSL: ack title

src/final-JATS-schematron.sch, src/final-JATS-schematron.xsl, src/final-package-JATS-schematron.sch, src/pre-JATS-schematron.sch, src/pre-JATS-schematron.xsl, src/schematron.sch, test/tests/gen/italic-genus/italic-genus-oocytes/italic-genus-oocytes.sch, test/tests/gen/org-ref-article-book-title/ref-article-title-organism-check/ref-article-title-organism-check.sch, test/tests/gen/org-title-kwd/article-title-organism-check/article-title-organism-check.sch, test/xspec/schematron.sch
Closes elifesciences/schematron-wiki#253
=> VOR: add slab links
