elifesciences/eLife-JATS-schematron

.travis.yml
src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/given-names-tests/given-names-test-5/given-names-test-5.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Use Saxon 9.9.1-5 (instead of 9.7.0-14) for CI tests
- Upgrade given-names-test-5 from warning to error

Minor changes

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/country-tests/gen-country-test/fail.xml
test/tests/gen/country-tests/gen-country-test/gen-country-test.sch
test/tests/gen/country-tests/gen-country-test/pass.xml
test/tests/gen/meta-value-tests/custom-meta-test-7/custom-meta-test-7.sch
test/tests/gen/meta-value-tests/custom-meta-test-7/fail.xml
test/tests/gen/meta-value-tests/custom-meta-test-7/pass.xml
test/tests/gen/pub-id-tests/pub-id-test-2/fail.xml
test/tests/gen/pub-id-tests/pub-id-test-2/pass.xml
test/tests/gen/pub-id-tests/pub-id-test-2/pub-id-test-2.sch
test/tests/gen/ref-article-title-tests/article-title-correction-check/article-title-correction-check.sch
test/tests/gen/ref-article-title-tests/article-title-correction-check/fail.xml
test/tests/gen/ref-article-title-tests/article-title-correction-check/pass.xml
test/tests/gen/test-title-group/article-title-test-11/article-title-test-11.sch
test/tests/gen/test-title-group/article-title-test-11/fail.xml
test/tests/gen/test-title-group/article-title-test-11/pass.xml
test/tests/gen/website-tests/github-web-test/fail.xml
test/tests/gen/website-tests/github-web-test/github-web-test.sch
test/tests/gen/website-tests/github-web-test/pass.xml
test/xspec/schematron.sch

- Allow `#` in dois, such as `10.1002/(SICI)1096-9861(19970414)380:3<373::AID-CNE6>3.0.CO;2-#`
- Exclude Sci corr articles from `article-title-test-11`
- Remove full stops in `et al.` for `custom-meta-test-7`
- Add link to `countries.xml` for `gen-country-test` message.
- Update `article-title-correction-check` to include 'Erratum'.
- Fix typo in message for `github-web-test`

fix minor issues

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/graphic-tests/graphic-test-1/fail.xml
test/tests/gen/graphic-tests/graphic-test-1/graphic-test-1.sch
test/tests/gen/graphic-tests/graphic-test-1/pass.xml
test/tests/gen/graphic-tests/graphic-test-2/fail.xml
test/tests/gen/graphic-tests/graphic-test-2/graphic-test-2.sch
test/tests/gen/graphic-tests/graphic-test-2/pass.xml
test/tests/gen/graphic-tests/graphic-test-3/fail.xml
test/tests/gen/graphic-tests/graphic-test-3/graphic-test-3.sch
test/tests/gen/graphic-tests/graphic-test-3/pass.xml
test/tests/gen/graphic-tests/graphic-test-4/fail.xml
test/tests/gen/graphic-tests/graphic-test-4/pass.xml
test/tests/gen/graphic-tests/graphic-test-5/fail.xml
test/tests/gen/graphic-tests/graphic-test-5/graphic-test-5.sch
test/tests/gen/graphic-tests/graphic-test-5/pass.xml
test/tests/gen/graphic-tests/graphic-test-6/fail.xml
test/tests/gen/graphic-tests/graphic-test-6/graphic-test-6.sch
test/tests/gen/graphic-tests/graphic-test-6/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Include `<inline-graphic>` in `graphic-tests`
- Add `graphic-test-6` to maintain distinct image files

graphic conformance

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/math-tests/math-test-13/fail.xml
test/tests/gen/math-tests/math-test-13/math-test-13.sch
test/tests/gen/math-tests/math-test-13/pass.xml
test/tests/gen/math-tests/math-test-17/fail.xml
test/tests/gen/math-tests/math-test-17/math-test-17.sch
test/tests/gen/math-tests/math-test-17/pass.xml
test/tests/gen/test-title-group/article-title-test-1/article-title-test-1.sch
test/tests/gen/test-title-group/article-title-test-1/fail.xml
test/tests/gen/test-title-group/article-title-test-1/pass.xml
test/tests/gen/test-title-group/article-title-test-2/article-title-test-2.sch
test/tests/gen/test-title-group/article-title-test-2/fail.xml
test/tests/gen/test-title-group/article-title-test-2/pass.xml
test/tests/gen/test-title-group/article-title-test-3/fail.xml
test/tests/gen/test-title-group/article-title-test-3/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Downgrade `article-title-test-2`
- Improve article-title messages
- Update `math-test-13` to account for square root symbols
- Add `math-test-17` for square root symbols

Fixes and improvements

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/missing-ref-cited/missing-ref-in-text-test/missing-ref-in-text-test.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Add mistakenly removed `unlinked-ref-cite-pattern`

Re-add missing pattern

---

Dockerfile
README.md
validator/.basex

Added an initial Docker build file that can build a container dervied from the 'basexhttp' container that
can be used to validate XML against eLife's schematrons files.

feat: Build a basic working container

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/insight-related-article-tests/insight-box-test-1/fail.xml
test/tests/gen/insight-related-article-tests/insight-box-test-1/insight-box-test-1.sch
test/tests/gen/insight-related-article-tests/insight-box-test-1/pass.xml
test/tests/gen/related-articles-conformance/related-articles-test-10/fail.xml
test/tests/gen/related-articles-conformance/related-articles-test-10/pass.xml
test/tests/gen/related-articles-conformance/related-articles-test-10/related-articles-test-10.sch
test/tests/gen/rrid-org-code/code-test/code-test.sch
test/tests/gen/rrid-org-code/code-test/fail.xml
test/tests/gen/rrid-org-code/code-test/pass.xml
test/tests/gen/supplementary-material-tests/supplementary-material-test-10/fail.xml
test/tests/gen/supplementary-material-tests/supplementary-material-test-10/pass.xml
test/tests/gen/supplementary-material-tests/supplementary-material-test-10/supplementary-material-test-10.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- feat: Add general warning for reporting standard files (`supplementary-material-test-10`).
- feat: Add error for non-distinct related article links (`related-articles-test-10`).
- feat: Add warning for insight boxed-text citation conformance (`insight-box-test-1`).
- fix: Don't fire `code-test` when `<code>` is present as a descendant of `<p>`.
- fix: Update value supplied in `conf-doi-test-1` message.

feat: Add more tests

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/journals.xml
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/source-data-specific-tests/fig-data-test-1/fail.xml
test/tests/gen/source-data-specific-tests/fig-data-test-1/fig-data-test-1.sch
test/tests/gen/source-data-specific-tests/fig-data-test-1/pass.xml
test/tests/gen/test-title-group/article-title-test-1/article-title-test-1.sch
test/tests/gen/test-title-group/article-title-test-10/article-title-test-10.sch
test/tests/gen/test-title-group/article-title-test-11/article-title-test-11.sch
test/tests/gen/test-title-group/article-title-test-12/article-title-test-12.sch
test/tests/gen/test-title-group/article-title-test-2/article-title-test-2.sch
test/tests/gen/test-title-group/article-title-test-3/article-title-test-3.sch
test/tests/gen/test-title-group/article-title-test-4/article-title-test-4.sch
test/tests/gen/test-title-group/article-title-test-5/article-title-test-5.sch
test/tests/gen/test-title-group/article-title-test-6/article-title-test-6.sch
test/tests/gen/test-title-group/article-title-test-7/article-title-test-7.sch
test/tests/gen/test-title-group/article-title-test-8/article-title-test-8.sch
test/tests/gen/test-title-group/article-title-test-9/article-title-test-9.sch
test/xspec/journals.xml
test/xspec/schematron.sch
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Exclude 1 letter words from `article-title-test-11`.
- Don't fire `fig-data-test-1` when  more than 1 fig citation is present.
- Updates to `journals.xml`

Improvements

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/p-punctuation/p-bracket-test/fail.xml
test/tests/gen/p-punctuation/p-bracket-test/p-bracket-test.sch
test/tests/gen/p-punctuation/p-bracket-test/pass.xml
test/tests/gen/res-data-sec/sec-test-3/fail.xml
test/tests/gen/res-data-sec/sec-test-3/pass.xml
test/tests/gen/res-data-sec/sec-test-3/sec-test-3.sch
test/xspec/schematron.sch
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Only fire `sec-test-3` when there is no citation or reference to a code repository.
- Fix typo in `p-bracket-test`

fix: typo and sec-test-3

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/award-group-tests/award-group-test-6/award-group-test-6.sch
test/tests/gen/award-group-tests/award-group-test-6/fail.xml
test/tests/gen/award-group-tests/award-group-test-8/award-group-test-8.sch
test/tests/gen/award-group-tests/award-group-test-8/fail.xml
test/tests/gen/award-group-tests/award-group-test-8/pass.xml
test/tests/gen/editorial-metadata/editorial-editors-presence/editorial-editors-presence.sch
test/tests/gen/editorial-metadata/editorial-editors-presence/fail.xml
test/tests/gen/editorial-metadata/editorial-editors-presence/pass.xml
test/tests/gen/funding-group-tests/funding-group-test-2/fail.xml
test/tests/gen/funding-group-tests/funding-group-test-2/pass.xml
test/tests/gen/funding-group-tests/funding-group-test-3/fail.xml
test/tests/gen/funding-group-tests/funding-group-test-3/funding-group-test-3.sch
test/tests/gen/funding-group-tests/funding-group-test-3/pass.xml
test/tests/gen/institution-wrap-tests/institution-id-test/fail.xml
test/tests/gen/institution-wrap-tests/institution-id-test/institution-id-test.sch
test/tests/gen/institution-wrap-tests/institution-id-test/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Do not allow editors in editorial articles `editorial-editors-presence`
- Split `award-group-test-6` into two separate tests for readability
- Message text edits in line with GitBook changes

feat: GitBook edits and editorial test

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/unallowed-symbol-tests/extra-full-stop-presence/extra-full-stop-presence.sch
test/tests/gen/unallowed-symbol-tests/extra-full-stop-presence/fail.xml
test/tests/gen/unallowed-symbol-tests/extra-full-stop-presence/pass.xml
test/tests/gen/unallowed-symbol-tests/extra-space-presence/extra-space-presence.sch
test/tests/gen/unallowed-symbol-tests/extra-space-presence/fail.xml
test/tests/gen/unallowed-symbol-tests/extra-space-presence/pass.xml
test/xspec/schematron.sch
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Don't fire `extra-full-stop-presence` when elipses are present.
- Don't fire `extra-space-presence` whn certain child elements are present.

fix: fixes for extra space and full stop tests

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-5/dec-letter-reply-test-5.sch
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-5/fail.xml
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-5/pass.xml
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-6/dec-letter-reply-test-6.sch
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-6/fail.xml
test/tests/gen/dec-letter-reply-content-tests/dec-letter-reply-test-6/pass.xml
test/tests/gen/reply-missing-disp-quote-tests-2/reply-missing-disp-quote-test-2/fail.xml
test/tests/gen/reply-missing-disp-quote-tests-2/reply-missing-disp-quote-test-2/pass.xml
test/tests/gen/reply-missing-disp-quote-tests-2/reply-missing-disp-quote-test-2/reply-missing-disp-quote-test-2.sch
test/tests/gen/unallowed-symbol-tests/operating-system-command-presence/fail.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Add test for incorrect italic text - `reply-missing-disp-quote-test-2`.
- Add a test for pseudo-code in sub-article paragraphs - `dec-letter-reply-test-6`
- Fire `dec-letter-reply-test-5` on paragraphs instead of at the sub-article level.

improvement: Add and refine sub-article checks

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/country-tests/gen-country-test/gen-country-test.sch
test/tests/gen/country-tests/n-korea-test/fail.xml
test/tests/gen/country-tests/n-korea-test/n-korea-test.sch
test/tests/gen/country-tests/n-korea-test/pass.xml
test/tests/gen/country-tests/s-korea-test/fail.xml
test/tests/gen/country-tests/s-korea-test/pass.xml
test/tests/gen/country-tests/s-korea-test/s-korea-test.sch
test/tests/gen/country-tests/taiwan-test/fail.xml
test/tests/gen/country-tests/taiwan-test/pass.xml
test/tests/gen/country-tests/taiwan-test/taiwan-test.sch
test/tests/gen/country-tests/united-kingdom-test-2/united-kingdom-test-2.sch
test/tests/gen/country-tests/united-states-test-1/united-states-test-1.sch
test/tests/gen/country-tests/united-states-test-2/united-states-test-2.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

perf: Move Taiwan tests to rules which already use both city and country as variables
perf: comment out currently unnecessary variable `$valid-country`
improvement: Add tests for South and North Korea in affiliations

perf and improvement: country tests

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/dec-letter-reviewer-tests/dec-letter-reviewer-test-6/dec-letter-reviewer-test-6.sch
test/tests/gen/dec-letter-reviewer-tests/dec-letter-reviewer-test-6/fail.xml
test/tests/gen/dec-letter-reviewer-tests/dec-letter-reviewer-test-6/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/schematron/final-JATS-schematron.sch
validator/webapp/schematron/pre-JATS-schematron.sch

- Downgrade `dec-letter-reviewer-test-6` to warning. In exceptional cases more than 3 reviewers are allowed.

fix: allow more than 3 reviewers

---

src/final-JATS-schematron.sch
src/pre-JATS-schematron.sch
test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml
xquery/elife.xqm

- Add an id to the start of each test message in pre and final versions. This is done in the refactor xQuery.

improvement: Add test ids to start of message text

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/dec-letter-front-tests/dec-letter-front-test-4/fail.xml
test/tests/gen/dec-letter-front-tests/dec-letter-front-test-4/pass.xml
test/tests/gen/latex-tests/latex-test/fail.xml
test/tests/gen/latex-tests/latex-test/latex-test.sch
test/tests/gen/latex-tests/latex-test/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Changes to `dec-letter-front-test-4` to account for review commons
- Add check for LaTeX
- Add GitBook links closes elifesciences/schematron-gitbook#72

improvement: Updates

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml
test/tests/gen/surname-tests/surname-test-5/fail.xml
test/tests/gen/surname-tests/surname-test-5/pass.xml
test/tests/gen/surname-tests/surname-test-5/surname-test-5.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Only fire `surname-test-5` in cases where the surname does not start with common lower case words, such as 'van', or 'de'.

fix: Less sensitivity for surname-test-5

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/abstract-word-count/abstract-word-count-restriction/abstract-word-count-restriction.sch
test/tests/gen/abstract-word-count/abstract-word-count-restriction/fail.xml
test/tests/gen/abstract-word-count/abstract-word-count-restriction/pass.xml
test/tests/gen/fig-group-tests/fig-group-test-2/fail.xml
test/tests/gen/fig-group-tests/fig-group-test-2/pass.xml
test/tests/gen/graphic-tests/graphic-test-8/fail.xml
test/tests/gen/graphic-tests/graphic-test-8/graphic-test-8.sch
test/tests/gen/graphic-tests/graphic-test-8/pass.xml
test/tests/gen/media-tests/media-test-11/fail.xml
test/tests/gen/media-tests/media-test-11/media-test-11.sch
test/tests/gen/media-tests/media-test-11/pass.xml
test/tests/gen/preprint-title-tests/biorxiv-test-2/biorxiv-test-2.sch
test/tests/gen/preprint-title-tests/biorxiv-test-2/fail.xml
test/tests/gen/preprint-title-tests/biorxiv-test-2/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-1/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-1/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-2/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-2/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-3/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-3/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-4/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-4/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- warning for abstracts with 151+ words - `abstract-word-count-restriction`
- Minor change to `fig-group-test-2`
- Do not allow ampersands in filenames for images or files - `graphic-test-8`, `media-test-11`.
- Add test for bioRxiv doi conformance - `biorxiv-test-2`.

improvement: Add more checks

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/mathbackground-tests/final-mathbackground-test-1/fail.xml
test/tests/gen/mathbackground-tests/final-mathbackground-test-1/final-mathbackground-test-1.sch
test/tests/gen/mathbackground-tests/final-mathbackground-test-1/pass.xml
test/tests/gen/mathbackground-tests/final-mathbackground-test-2/fail.xml
test/tests/gen/mathbackground-tests/final-mathbackground-test-2/final-mathbackground-test-2.sch
test/tests/gen/mathbackground-tests/final-mathbackground-test-2/pass.xml
test/tests/gen/mathbackground-tests/pre-mathbackground-test-1/fail.xml
test/tests/gen/mathbackground-tests/pre-mathbackground-test-1/pass.xml
test/tests/gen/mathbackground-tests/pre-mathbackground-test-1/pre-mathbackground-test-1.sch
test/tests/gen/mathbackground-tests/pre-mathbackground-test-2/fail.xml
test/tests/gen/mathbackground-tests/pre-mathbackground-test-2/pass.xml
test/tests/gen/mathbackground-tests/pre-mathbackground-test-2/pre-mathbackground-test-2.sch
test/tests/gen/sec-tests/sec-test-5/fail.xml
test/tests/gen/sec-tests/sec-test-5/pass.xml
test/tests/gen/sec-tests/sec-test-5/sec-test-5.sch
test/xspec/schematron.sch

- Only fire `mathbackground-tests` on elements with that attribute, in order to reduce number of tests carried out.
- Add GitHub link for `sec-test-5`.

perf: mathbackground-tests improvement

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/empty-attribute-test/empty-attribute-conformance/empty-attribute-conformance.sch
test/tests/gen/empty-attribute-test/empty-attribute-conformance/fail.xml
test/tests/gen/empty-attribute-test/empty-attribute-conformance/pass.xml
test/tests/gen/website-tests/github-web-test/fail.xml
test/tests/gen/website-tests/github-web-test/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec
validator/webapp/validator.xqm
xquery/elife.xqm

- Don't permit empty attributes - `empty-attribute-conformance`.
- Don't fire `github-web-test` for github.io links.
- Validator posts GitHub links as plain text

improvement: attribute conformance

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/contrib-tests/deceased-test-2/deceased-test-2.sch
test/tests/gen/digest-tests/digest-test-1/digest-test-1.sch
test/tests/gen/digest-tests/digest-test-1/fail.xml
test/tests/gen/digest-tests/digest-test-1/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Add warning for paras starting with lowercase letters in digests - `digest-test-1`.
- Add GitBook links for deceased page. Closes elifesciences/schematron-gitbook#89

improvement: digest and GitBook links

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/digest-tests/digest-test-1/digest-test-1.sch
test/tests/gen/digest-tests/digest-test-1/fail.xml
test/tests/gen/digest-tests/digest-test-1/pass.xml
test/tests/gen/rrid-link/final-rrid-spacing/final-rrid-spacing.sch
test/tests/gen/rrid-link/pre-rrid-spacing/pre-rrid-spacing.sch
test/tests/gen/rrid-org-code/rrid-test/rrid-test.sch
test/xspec/schematron.sch

- Add links for RRID tests. Closes elifesciences/schematron-gitbook#35
- Update message text for `digest-test-1`.

improvement: Add GitBook links

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/corresp-author-initial-test.sch
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/fail.xml
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/pass.xml
test/tests/gen/digest-tests/digest-test-1/fail.xml
test/tests/gen/digest-tests/digest-test-1/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Fire warning for any author with diacritics/marks in their name in an article which displays initials in the 'For correspondence' section of the PDF - `corresp-author-initial-test`.
- Fix message text in `digest-test-1`.

improvement: diacritic test

---

src/final-JATS-schematron.sch
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/schematron.sch
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/corresp-author-initial-test.sch
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/fail.xml
test/tests/gen/corresp-author-initial-tests/corresp-author-initial-test/pass.xml
test/tests/gen/disp-formula-tests/disp-formula-test-3/disp-formula-test-3.sch
test/tests/gen/disp-formula-tests/disp-formula-test-3/fail.xml
test/tests/gen/disp-formula-tests/disp-formula-test-3/pass.xml
test/tests/gen/disp-formula-tests/disp-formula-test-4/disp-formula-test-4.sch
test/tests/gen/disp-formula-tests/disp-formula-test-4/fail.xml
test/tests/gen/disp-formula-tests/disp-formula-test-4/pass.xml
test/tests/gen/elem-citation-patent/final-err-elem-cit-patent-11-1/fail.xml
test/tests/gen/elem-citation-patent/final-err-elem-cit-patent-11-1/final-err-elem-cit-patent-11-1.sch
test/tests/gen/elem-citation-patent/final-err-elem-cit-patent-11-1/pass.xml
test/tests/gen/elem-citation-patent/pre-err-elem-cit-patent-11-1/fail.xml
test/tests/gen/elem-citation-patent/pre-err-elem-cit-patent-11-1/pass.xml
test/tests/gen/elem-citation-patent/pre-err-elem-cit-patent-11-1/pre-err-elem-cit-patent-11-1.sch
test/tests/gen/ext-link-tests/url-conformance-test/fail.xml
test/tests/gen/ext-link-tests/url-conformance-test/pass.xml
test/tests/gen/ext-link-tests/url-conformance-test/url-conformance-test.sch
test/tests/gen/gen-das-tests/das-elem-cit-5/das-elem-cit-5.sch
test/tests/gen/gen-das-tests/das-elem-cit-5/fail.xml
test/tests/gen/gen-das-tests/das-elem-cit-5/pass.xml
test/tests/gen/res-data-sec/sec-test-3/fail.xml
test/tests/gen/res-data-sec/sec-test-3/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- Specify first `name` element in variable invocation of `e:get-name` to avoid fatal errors
- Fix for `url-conformance-test`
- Downgrade `disp-formula-test-3` to warning.
- Add error for instances of `<p><disp-formula>` (`disp-formula-test-4`) per elifesciences/issues#6130
- perf and fix for `res-data-sec`.
- Warning for same reference in both DAS and ref list - das-elem-cit-5
- Split `err-elem-cit-patent-11-1` into `pre` and `final` versions

improvement: new tests and fixes

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/xspec/schematron.sch

- Use 16 digit orcid instead of full url for `duplicate-member-orcid-test` and `duplicate-orcid-test` thereby ignoring http/https.

fix: ignore http/https in orcid duplicate check

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/rrid-org-code/cell-spacing-test/cell-spacing-test.sch
test/tests/gen/rrid-org-code/code-test/code-test.sch
test/tests/gen/rrid-org-code/diabetes-1-test/diabetes-1-test.sch
test/tests/gen/rrid-org-code/diabetes-2-test/diabetes-2-test.sch
test/tests/gen/rrid-org-code/equal-spacing-test/equal-spacing-test.sch
test/tests/gen/rrid-org-code/final-missing-url-test/final-missing-url-test.sch
test/tests/gen/rrid-org-code/org-test/org-test.sch
test/tests/gen/rrid-org-code/ring-diacritic-symbol-test/ring-diacritic-symbol-test.sch
test/tests/gen/rrid-org-code/rrid-test/fail.xml
test/tests/gen/rrid-org-code/rrid-test/pass.xml
test/tests/gen/rrid-org-code/rrid-test/rrid-test.sch
test/tests/gen/rrid-org-code/unlinked-url/unlinked-url.sch
test/tests/gen/rrid-org-code/year-style-test/year-style-test.sch
test/xspec/schematron.sch

Temporarily permit both 'identifiers.org/RRID/RRID:' and 'scicrunch.org/resolver/' type links for RRIDs before switching to only the former.

fix: change to RRID capture

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/inline-formula-tests/inline-formula-test-2/fail.xml
test/tests/gen/inline-formula-tests/inline-formula-test-2/inline-formula-test-2.sch
test/tests/gen/inline-formula-tests/inline-formula-test-2/pass.xml
test/tests/gen/inline-formula-tests/inline-formula-test-3/fail.xml
test/tests/gen/inline-formula-tests/inline-formula-test-3/inline-formula-test-3.sch
test/tests/gen/inline-formula-tests/inline-formula-test-3/pass.xml
test/tests/gen/unlinked-object-cite/text-v-object-cite-test/text-v-object-cite-test.sch
test/xspec/schematron.sch

- Don't fire `inline-formula-test-2` and `inline-formula-test-3` incases where they are immediately preceded/followed by display formulae.
- Account for no-break spaces in the text in `text-v-object-cite-test`.

fix: two minor fixes

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/supplementary-material-title-tests/supplementary-material-title-test-2/fail.xml
test/tests/gen/supplementary-material-title-tests/supplementary-material-title-test-2/pass.xml
test/tests/gen/supplementary-material-title-tests/supplementary-material-title-test-2/supplementary-material-title-test-2.sch
test/tests/gen/xref-target-tests/other-xref-target-test/fail.xml
test/tests/gen/xref-target-tests/other-xref-target-test/other-xref-target-test.sch
test/tests/gen/xref-target-tests/other-xref-target-test/pass.xml
test/xspec/schematron.sch

- Permit question mark and full stop for `supplementary-material-title-test-2`.
- No longer permit `element-citation` as a target of `<xref ref-type="other">` in `other-xref-target-test`.

fix: minor fixes

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/country-tests/gen-country-test/gen-country-test.sch
test/tests/gen/country-tests/n-korea-test/n-korea-test.sch
test/tests/gen/country-tests/s-korea-test/s-korea-test.sch
test/tests/gen/country-tests/singapore-test-1/singapore-test-1.sch
test/tests/gen/country-tests/taiwan-test/taiwan-test.sch
test/tests/gen/country-tests/united-kingdom-test-2/united-kingdom-test-2.sch
test/tests/gen/country-tests/united-states-test-1/united-states-test-1.sch
test/tests/gen/country-tests/united-states-test-2/united-states-test-2.sch
test/tests/gen/institution-tests/UC-no-test-2/UC-no-test-2.sch
test/tests/gen/institution-tests/UC-no-test-3/UC-no-test-3.sch
test/tests/gen/institution-tests/UC-no-test1/UC-no-test1.sch
test/tests/gen/institution-tests/institution-replacement-character-presence/institution-replacement-character-presence.sch
test/tests/gen/institution-tests/institution-street-presence/institution-street-presence.sch
test/xspec/schematron.sch

- Avoid fatal error when an affiliation has numerous cities

fix: avoid fatal error

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-4/fail.xml
test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-4/pass.xml
test/tests/gen/supp-file-xref-conformance/supp-file-xref-conformity-4/supp-file-xref-conformity-4.sch
test/xspec/schematron.sch
test/xspec/schematron.xspec

- `supp-file-xref-conformity-4` now a warning because of audio files.

downgrade supp-file-xref-conformity-4

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/disp-formula-tests/disp-formula-test-4/disp-formula-test-4.sch
test/tests/gen/disp-formula-tests/disp-formula-test-4/fail.xml
test/tests/gen/disp-formula-tests/disp-formula-test-4/pass.xml
test/xspec/schematron.sch

`disp-formula-test-4` no longer fires when a `disp-formula` is included as the first item of a `p` element in a `list-item`.

exclude formulae in lists for disp-formula-test-4

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/fail.xml
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/medicine-abstract-conformance.sch
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/pass.xml
test/xspec/schematron.sch

- More specific context for `medicine-abstract-conformance` so that it only fires on the common/garden abstract

fix: medicine-abstract-conformance

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/fail.xml
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/medicine-abstract-conformance.sch
test/tests/gen/medicine-abstract-tests/medicine-abstract-conformance/pass.xml
test/tests/gen/pub-history-tests/preprint-flag/fail.xml
test/tests/gen/pub-history-tests/preprint-flag/pass.xml
test/tests/gen/pub-history-tests/preprint-flag/preprint-flag.sch
test/tests/gen/test-editor-contrib-group/editor-conformance-2/fail.xml
test/tests/gen/test-editor-contrib-group/editor-conformance-2/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- downgrade `editor-conformance-2` to waring
- Add info check `preprint-flag`
- `medicine-abstract-conformance` to stay as warning

fix: various updates

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/unlinked-object-cite/text-v-object-cite-test/text-v-object-cite-test.sch
test/xspec/schematron.sch

- `text-v-object-cite-test` no longer fatal errors if labels contain single brackets

fix: bug with text-v-object-cite-test

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/disp-formula-tests/disp-formula-test-4/disp-formula-test-4.sch
test/tests/gen/disp-formula-tests/disp-formula-test-4/fail.xml
test/tests/gen/disp-formula-tests/disp-formula-test-4/pass.xml
test/tests/gen/unlinked-object-cite/text-v-object-cite-test/text-v-object-cite-test.sch
test/tests/gen/vid-xref-conformance/vid-xref-conformity-1/vid-xref-conformity-1.sch
test/tests/gen/vid-xref-conformance/vid-xref-conformity-2/vid-xref-conformity-2.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-10/vid-xref-test-10.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-11/vid-xref-test-11.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-2/vid-xref-test-2.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-3/vid-xref-test-3.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-4/vid-xref-test-4.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-5/vid-xref-test-5.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-6/vid-xref-test-6.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-7/vid-xref-test-7.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-8/vid-xref-test-8.sch
test/tests/gen/vid-xref-conformance/vid-xref-test-9/vid-xref-test-9.sch
test/xspec/schematron.sch

- Fix for `disp-formula-test-4`. Permit parent p as first piece of content if container is a box.
- `text-v-object-cite-test` - slight refinement
- Account for numerous ids in `rid` for `vid-xref-conformity-2`.

various fixes

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/elem-citation-software/elem-cit-software-pub-id-ext-link/fail.xml
test/tests/gen/elem-citation-software/elem-cit-software-pub-id-ext-link/pass.xml
test/tests/gen/elem-citation/self-cite-2/fail.xml
test/tests/gen/elem-citation/self-cite-2/pass.xml
test/tests/gen/pub-id-tests/indistinct-pub-ids/fail.xml
test/tests/gen/pub-id-tests/indistinct-pub-ids/indistinct-pub-ids.sch
test/tests/gen/pub-id-tests/indistinct-pub-ids/pass.xml
test/tests/gen/software-ref-tests/ref-software-test-7/fail.xml
test/tests/gen/software-ref-tests/ref-software-test-7/pass.xml
test/xspec/schematron.sch
test/xspec/schematron.xspec

- `self-cite-1` no longer causes fatal error if `element-citation` has more than one `pub-id[@pub-id-type='doi']`
- Add `indistinct-pub-ids` to catch refs with more than one pub-id.

fix: no fatal error if more than one doi in ref

---

src/final-JATS-schematron.sch
src/final-JATS-schematron.xsl
src/final-package-JATS-schematron.sch
src/pre-JATS-schematron.sch
src/pre-JATS-schematron.xsl
src/schematron.sch
test/tests/gen/event-desc-tests/event-desc-content-2/fail.xml
test/tests/gen/event-desc-tests/event-desc-content-2/pass.xml
test/tests/gen/meta-value-tests/final-custom-meta-test-9/fail.xml
test/tests/gen/meta-value-tests/final-custom-meta-test-9/final-custom-meta-test-9.sch
test/tests/gen/meta-value-tests/final-custom-meta-test-9/pass.xml
test/tests/gen/meta-value-tests/pre-custom-meta-test-9/fail.xml
test/tests/gen/meta-value-tests/pre-custom-meta-test-9/pass.xml
test/tests/gen/meta-value-tests/pre-custom-meta-test-9/pre-custom-meta-test-9.sch
test/tests/gen/ro-kwd-tests/kwd-dupe-test/fail.xml
test/tests/gen/ro-kwd-tests/kwd-dupe-test/pass.xml
test/xspec/schematron.sch

fire `custom-meta-test-9` variants if `et al.` is in impact statement

chore: change to custom-meta-test-9

---

src/preprint-changes.xsl

`aff` can be a child of `article-meta`. This isn't preferred capture, but it's schema valid so should be supported by the XSL

RP XSL - account for different aff capture

---

src/rp-schematron-base.sch
src/rp-schematron.sch
src/rp-schematron.xsl
test/tests/rp/p-ref-checks/missing-ref-in-text-test/fail.xml
test/tests/rp/p-ref-checks/missing-ref-in-text-test/missing-ref-in-text-test.sch
test/tests/rp/p-ref-checks/missing-ref-in-text-test/pass.xml
test/xspec/rp-schematron.sch

- Exclude cases where the article exclusively uses digits for reference citations

RP: refine scope of p-ref-checks
